services:
  financial-report-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-report-api
    ports:
      - "8000:8000"
    volumes:
      - ./excel_ocr/input:/app/excel_ocr/input
      - ./excel_ocr/output:/app/excel_ocr/output
      - ./excel_ocr/uploads:/app/excel_ocr/uploads
      - ./:/app/data
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
