services:
  financial-report-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-report-api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/src/uploads
      - ./data:/app/src/data
      - ./.env:/app/.env
      - ./gcs-credentials.json:/app/gcs-credentials.json
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
