export const financialIndicators = {
  balanceSheet: [
    "Cash and Cash Equivalents",
    "Short-term Investments",
    "Accounts Receivable",
    "Inventories",
    "Other Current Assets",
    "Total Current Assets",
    "Long-term Investments",
    "Property, Plant and Equipment (Net)",
    "Intangible Assets",
    "Other Non-current Assets",
    "Total Non-current Assets",
    "Total Assets",
    "Short-term Debt",
    "Accounts Payable",
    "Accrued Liabilities",
    "Other Current Liabilities",
    "Total Current Liabilities",
    "Long-term Debt",
    "Deferred Tax Liabilities",
    "Other Non-current Liabilities",
    "Total Non-current Liabilities",
    "Total Liabilities",
    "Common Stock",
    "Retained Earnings",
    "Other Equity",
    "Total Equity",
    "Total Liabilities and Equity"
  ],
  incomeStatement: [
    "Revenue",
    "Cost of Goods Sold",
    "Gross Profit",
    "Selling Expenses",
    "General and Administrative Expenses",
    "Research and Development Expenses",
    "Operating Profit",
    "Interest Income",
    "Interest Expense",
    "Other Income (Expenses)",
    "Profit Before Tax",
    "Income Tax Expense",
    "Net Profit"
  ],
  cashFlowStatement: [
    "Net Income",
    "Depreciation and Amortization",
    "Change in Working Capital",
    "Cash Flow from Operating Activities",
    "Capital Expenditures",
    "Proceeds from Sale of Assets",
    "Cash Flow from Investing Activities",
    "Proceeds from Borrowings",
    "Repayment of Debt",
    "Dividends Paid",
    "Cash Flow from Financing Activities",
    "Net Change in Cash"
  ]
}